### ISSUE TITLE
Source Examples Repository Missing

### ISSUE THREAD

**Issue by ojnc** [softchris/softchris.github.io#4]
Your eBook is superb and I read a lot of it.
Very easy to read and no flab!

Do you have a repo with the source code in your eBook organized like softchris-examples?
Something very basic and simple like most paid for books

I may have missed it. Please advise.

For example [Forms II - validation](https://softchris.github.io/books/react/forms-validation/) is very nice
I wanted to try it without copy pasting the code and creating a package.json etc

Thanks
Jayanta@Kolkata

**Comment by softchris** [comment]
That's a real good idea. I'll look into creating that @ojnc :) Thanks for suggesting

**Comment by ojnc** [comment]
Thanks!
Meanwhile I read your blog article on cypress which is also excellent.
I arrived via Google but seeing "SoftChris" knew same bloke!
